merge(feature-test-1): squash merged commits from feature-test-1 [12:18]

diff --git a/.github/workflows/simple-git-diff.yml b/.github/workflows/simple-git-diff.yml
--- a/.github/workflows/simple-git-diff.yml
+++ b/.github/workflows/simple-git-diff.yml
@@ -60,16 +60,15 @@ jobs:
       env:
         CHANGELOG: ${{ env.CHANGELOG }}
 
-    # - name: Fail Build
-    #   run: |
-    #     echo "Simulating build failure"
-    #     exit 1
-    #   env:
+    - name: Fail Build
+      run: |
+        echo "Simulating build failure"
+        exit 1
 
   post-git-diff:
     name: Post Job Save/Remove SHA
     runs-on: ubuntu-latest
-    needs: git-diff
+    needs: [git-diff, simulate-build]
     if: always()
     env:
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY }}
@@ -79,12 +78,12 @@ jobs:
       REF_FILE_NAME: last_failed_before_ref.txt
     steps:
       - name: Save BEFORE_REF to S3 on failure
-        if: needs.git-diff.result == 'failure'
+        if: needs.simulate-build.result == 'failure'
         run: |
           echo "${{ github.event.before }}" > $REF_FILE_NAME
           aws s3 cp $REF_FILE_NAME s3://$AWS_BUCKET_NAME/changelog/${{ github.repository }}/${{ github.ref_name }}/$REF_FILE_NAME
 
       - name: Delete BEFORE_REF from S3 on success
-        if: needs.git-diff.result == 'success'
+        if: needs.simulate-build.result == 'success'
         run: |
           aws s3 rm s3://$AWS_BUCKET_NAME/changelog/${{ github.repository }}/${{ github.ref_name }}/$REF_FILE_NAME || true
