merge(feature-test-1): squash merged commits from feature-test-1 [23:06]

diff --git a/.github/workflows/test-git-diff.yml b/.github/workflows/test-git-diff.yml
--- a/.github/workflows/test-git-diff.yml
+++ b/.github/workflows/test-git-diff.yml
@@ -20,7 +20,7 @@ jobs:
           fetch-depth: 0
       - name: Download previous BEFORE_REF from S3 (if any)
         run: |
-          aws s3 cp s3://everbeat-github/changelog/${{ github.ref }}/last_failed_before_ref.txt last_failed_before_ref.txt || true
+          aws s3 cp s3://everbeat-github/changelog/${{ github.repository }}/${{ github.ref }}/last_failed_before_ref.txt last_failed_before_ref.txt || true
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
@@ -47,11 +47,18 @@ jobs:
         env:
           CHANGELOG: ${{ env.CHANGELOG }}
 
+      - name: Simulate failure on dev only
+        if: github.ref_name == 'dev'
+        run: |
+          echo "💥 Simulating failure on dev branch"
+          exit 1
+
+
       - name: Save BEFORE_REF to S3 on failure
         if: failure()
         run: |
           echo "${{ github.event.before }}" > last_failed_before_ref.txt
-          aws s3 cp last_failed_before_ref.txt s3://everbeat-github/changelog/${{ github.ref }}/last_failed_before_ref.txt
+          aws s3 cp last_failed_before_ref.txt s3://everbeat-github/changelog/${{ github.repository }}/${{ github.ref }}/last_failed_before_ref.txt
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
