merge(feature-test-1): squash merged commits from feature-test-1 [23:10]

diff --git a/.github/workflows/test-git-diff.yml b/.github/workflows/test-git-diff.yml
--- a/.github/workflows/test-git-diff.yml
+++ b/.github/workflows/test-git-diff.yml
@@ -24,7 +24,7 @@ jobs:
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
-          AWS_DEFAULT_REGION: your-region
+          AWS_DEFAULT_REGION: us-west-2
       - name: Get Commit Messages
         env:
           BEFORE_REF: ${{ github.event.before }}
@@ -47,11 +47,11 @@ jobs:
         env:
           CHANGELOG: ${{ env.CHANGELOG }}
 
-      # - name: Simulate failure on dev only
-      #   if: github.ref_name == 'dev'
-      #   run: |
-      #     echo "💥 Simulating failure on dev branch"
-      #     exit 1
+      - name: Simulate failure on dev only
+        if: github.ref_name == 'dev'
+        run: |
+          echo "💥 Simulating failure on dev branch"
+          exit 1
 
 
       - name: Save BEFORE_REF to S3 on failure
